services:
  db:
    image: mariadb:11
    container_name: adb_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  wordpress:
    image: wordpress:6.6-php8.2-apache
    container_name: adb_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DEBUG: 1
    ports:
      - "8081:80"      # WordPress em http://localhost:8081
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wpnet

  adminer:
    image: adminer:4
    container_name: adb_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"    # Adminer em http://localhost:8080
    networks:
      - wpnet

  vite:
    container_name: adb_vite
    build:
      context: .
      dockerfile: Dockerfile.vite
    working_dir: /var/www/html/wp-content/themes/arquivo-do-bem
    depends_on:
      - wordpress
    ports:
      - "${VITE_PORT:-5173}:5173"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WP_ORIGIN: http://wordpress
      VITE_PORT: 5173
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    networks:
      - wpnet





volumes:
  db_data:

networks:
  wpnet:
